// same array in public/scripts/scripts.js
let yeaRangeRef = new Date().getFullYear();

const constants = {
  pwRounds: 16,

  weekdays: [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
  ],
  months: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  yearRange: [
    yeaRangeRef - 2,
    yeaRangeRef - 1,
    yeaRangeRef,
    yeaRangeRef + 1,
    yeaRangeRef + 2,
  ],
  eventTypes: {
    task: "task",
    meeting: "meeting",
    notes: "notes",
    reminder: "reminder",
  },
  stringLimits: {
    title: 100,
    textBody: 200,
    tag: 20,
    password: 8,
  },
  timeslots: [
    "1:00 AM",
    "2:00 AM",
    "3:00 AM",
    "4:00 AM",
    "5:00 AM",
    "6:00 AM",
    "7:00 AM",
    "8:00 AM",
    "9:00 AM",
    "10:00 AM",
    "11:00 AM",
    "12:00 PM",
    "1:00 PM",
    "2:00 PM",
    "3:00 PM",
    "4:00 PM",
    "5:00 PM",
    "6:00 PM",
    "7:00 PM",
    "8:00 PM",
    "9:00 PM",
    "10:00 PM",
    "11:00 PM",
    "12:00 AM",
  ],
};

export default constants;
